openapi: 3.0.3
info:
  version: 1.0.0
  title: Stat API
  description: Stat api 
  x-sla:
    $ref: ./plans.yaml
security:
  - BearerAuth: []
paths:
  /api/v1/stats:
    x-router-controller: statController
    get:
      description: Returns all stats
      operationId: getStats
      responses:
        200:
          description: Stat list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/stat'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
                 
  /api/v1/stats/{id}:
    x-router-controller: statController
    get:
      description: Returns a single stat by its id
      operationId: findByid
      parameters:
        - required: true
          name: id
          description: id of the stat to fetch
          in: path
          schema:
            type: number
      responses:
        200:
          description: Stat found by id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stat'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    stat:
        type: object
        required:
          - period
        properties:
          period:
            type: number
          territory:
            type: string
          finished_house:
            type: number
          half_price_m_two:
            type: number
          tourist:
            type: number
    error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
      additionalProperties: true